## Now casting script for running EpiNow2 on NSW COVID case data

# Packages ----------------------------------------------------------------
require(EpiNow2, quietly = TRUE)
require(tidyverse, quietly = TRUE)
require(lubridate, quietly = TRUE)
require(future, quietly = TRUE)

# Functions ---------------------------------------------------------------
source("code/GetCases.R")
source("code/LoadData.R")
source("code/SpecifyRegions.R")

# User options ============================================================
regionLevel <- "LGA" # "NSW", "Sydney",  or "LGA"
startDate <- "2021-06-01" # Filter to after this date (to speed up 
                          # computation)
dateRun <- NULL # Run to this date: NULL = last date in data file
regionOptions <- SpecifyRegions(regionLevel, "TestLGAs") 
specificRegions <- regionOptions[[1]]
resultsFolder <- regionOptions[[2]] # or manually add
dataOption <- "file" # "nsw-website" or "file"


# =========================================================================

# Set-up outputs ----------------------------------------------------------
if ((regionLevel == "LGA" & length(specificRegions) > 1) |
    (regionLevel == "LGA" & specificRegions[1] == "all")) {
  regionalRun <- TRUE
  epiFunction <- EpiNow2::regional_epinow
} else {
  regionalRun <- FALSE
  epiFunction <- EpiNow2::epinow
}

dir.create(file.path("results", resultsFolder), showWarnings = FALSE)

# Load raw case data ------------------------------------------------------
print("Retrieving raw cases data...")
nsw_raw_cases <- LoadData(dataOption)

# Get cases we want -------------------------------------------------------
print("Getting cases...")

cases <- GetCases(nsw_raw_cases, dataOption, regionLevel, startDate, 
  regions = specificRegions) %>%
  arrange(region)

if(!is.null(dateRun)) {
  cases <- reported_cases %>% 
    filter(date <= dateRun)
}

if (!regionalRun) {
  cases <- reported_cases %>%
    select(-region)
}

# Load delays -------------------------------------------------------------
print("Loading delay definitions...")

# TODO: Add code for local delay definitions
reporting_delay <- list(mean = convert_to_logmean(4, 1),
                        mean_sd = 0.1,
                        sd = convert_to_logsd(4, 1),
                        sd_sd = 0.1,
                        max = 15)

generation_time <- EpiNow2::get_generation_time(disease = "SARS-CoV-2", 
  source = "ganyani")
incubation_period <- EpiNow2::get_incubation_period(disease = "SARS-CoV-2", 
  source = "lauer")

# Set up cores ------------------------------------------------------------
print("Setting up EpiNow...")
if (!interactive()){
  options(future.fork.enable = TRUE)
}

future::plan("multiprocess", workers = round(future::availableCores() / 2))

# Run EpiNow --------------------------------------------------------------

estimates <- epiFunction(reported_cases = cases, 
  generation_time = generation_time,
  delays = delay_opts(incubation_period, reporting_delay),
  # Need to tweak prior for Rt I would think
  rt = rt_opts(prior = list(mean = 1.5, sd = 0.5)),
  stan = stan_opts(),
  horizon = 14, 
  target_folder = file.path("results", resultsFolder),
  logs = file.path("logs", Sys.Date()),
  return_output = TRUE, 
  verbose = TRUE)

# Save everything in the results folder
save(regionLevel, startDate, dateRun, specificRegions, cases, estimates,
  resultsFolder, generation_time, incubation_period, reporting_delay,
  file = file.path("results", resultsFolder, paste0("Epinow_results-", 
    format(Sys.time(), "%Y-%m-%d_%H-%M-%S"))))

# Summarise results -------------------------------------------------------

# Commands for looking at individual region results
# > summary(estimates)
# > plot(estimates)
# > summary(estimates, type = "parameters", params = "R")

# For regional results we can generate a regional summary
if (regionalRun) {
  # The following command won't run if some regions do not have all the 
  # results files. If you strike an error check that all the result folders 
  # and files have been generated by EpiNow. 
  print("Producing regional summary ...")
  
  RegionalSummary <- function(reported_cases, folder) {
    
    results_dir = file.path("results", folder)
    target_date = "latest"
    summary_dir =  file.path(results_dir, "regional-summary", "latest")
    
    EpiNow2::regional_summary(
      regional_output = NULL,
      reported_cases = reported_cases,
      results_dir = results_dir,
      summary_dir = summary_dir,
      target_date = target_date)
  }
  
  RegionalSummary(cases, resultsFolder)
  
}
