# Now casting script for running EpiNow2 on NSW COVID case data
# =============================================================

```{r Set-up}
# Open as a project (setting working directory to source and restarting R)

# Packages
require(EpiNow2, quietly = TRUE)
require(tidyverse, quietly = TRUE)
require(lubridate, quietly = TRUE)
require(future, quietly = TRUE)

# Functions 
source("code/LoadData.R")
source("code/GetCases.R")
source("code/SpecifyRegions.R")
source("code/RegionalSummary.R")
source("code/regional_summary_NSW.R")
source("code/plot_summary_NSW.R")
source("code/RegionsCumulativeReports.R")
source("code/Functions.R")
```

```{r User inputs}
# Chunk where user enters all the input options for running EpiNow2
# regionLevel <- "NSW" # "NSW", "Sydney",  or "LGA"

dateRun <- NULL # Run to this date: NULL = last date in data file
startDate <- "2021-06-01" # Filter to after this date (to speed up 
# computation)

dataOption <- "nsw_website" # "nsw_website" or "file"
delayOption <- "nsw_data" # nsw_data (default), "testing", "international"

specificRegions <- SpecifyRegions("all")[[1]]
resultsFolder <- SpecifyRegions("all")[[2]] 

# specificRegions <- c("NSW", "Sutherland Shire (A)")
# resultsFolder <- "Testing"

```

```{r Sort out case data}
# Load raw case data 
print("Retrieving raw cases data...")
nsw_raw_cases <- LoadData(dataOption)

# Save website data
if (dataOption == "nsw_website") {
  write_csv(nsw_raw_cases, file = file.path("data", 
    paste0("NSW_Health_Website_Data-", Sys.Date())))
}
# Get cases we want 
print("Getting cases...")

cases <- GetCases(nsw_raw_cases, dataOption, startDate) 

# Filter out dates we don't need
if(!is.null(dateRun)) {
  cases <- cases %>% 
    filter(date <= dateRun)
}

# Filter out regions we are not interested in
if (specificRegions[1] != "all") {
  cases <- cases %>%
    filter(region %in% specificRegions)
} 

```

```{r Set-up outputs}
# Separate out specific regions
nswCases <- filter(cases, region == "NSW")
#sydneyCases <- filter(cases, region == "Sydney")
#regionalCases <- filter(cases, region == "Regional")
lgaCases <- filter(cases, !(region %in% c("NSW", "Sydney", "Regional")))
lgaRegions <- unique(lgaCases$region)

multiLGArun <- ifelse(length(lgaRegions) > 1, TRUE, FALSE)

dateCases <- max(cases$date)

dir.create(file.path("results", resultsFolder), showWarnings = FALSE)
```

```{r Load EpiNow delay parameters}
print("Loading delay definitions...")

if (delayOption == "nsw_data") {
  # Load delay_defs fitted from local NSW data
  reporting_delay <- readRDS("data/local_delays.rds")
} else if (delayOption == "international") {
  # Out of date delay estimate from international sources
  reporting_delay <- readRDS("data/international_delays.rds")
} else if (delayOption == "testing") {
  # Basic set-up for testing purposes
  reporting_delay <- list(mean = EpiNow2::convert_to_logmean(4, 1),
    mean_sd = 0.1, sd = EpiNow2::convert_to_logsd(4, 1),
    sd_sd = 0.1, max = 15)
} else {
  stop("Unknown reporting delay option")
}

# Other delays from the literature
generation_time <- EpiNow2::get_generation_time(disease = "SARS-CoV-2", 
  source = "ganyani")
incubation_period <- EpiNow2::get_incubation_period(disease = "SARS-CoV-2", 
  source = "lauer")
```

```{r Set-up simulations}
print("Setting up EpiNow...")
# Use future package to run things in parallel

options(future.fork.enable = TRUE)
future::plan("multiprocess", workers = round(future::availableCores() / 2))
# ncores <- round(future::availableCores() / 2)
```

```{r Run EpiNow}
# Initialize
nswEstimates <- NULL
# sydneyEstimates <- NULL
# regionalEstimates <- NULL
lgaEstimates <- NULL

print("Running EpiNow...")

# Run Epinow
if (nrow(nswCases) != 0) {
  print("Generating NSW estimates...")
  nswEstimates <- EpiNow2::epinow(
    reported_cases =  dplyr::select(nswCases, -region), 
    generation_time = generation_time,
    delays = delay_opts(incubation_period, reporting_delay),
    # Using default Rt prior
    rt = rt_opts(prior = list(mean = 1, sd = 0.5)),
    stan = stan_opts(),
    target_folder = file.path("results", resultsFolder, "NSW"),
    logs = file.path("logs", Sys.Date()),
    return_output = TRUE, 
    verbose = TRUE
  )
  
  # Run function to save CSV file of key indicators 
  keyEstimates <- GetKeyEstimates(nswEstimates, multiLGArun)
  
  SaveAllIndicators(keyEstimates, 
    file.path("results", resultsFolder, "NSW"),
    dateCases)
  SaveAllIndicators(keyEstimates, 
    file.path("results", resultsFolder, "NSW"), 
    "latest")
}

# TODO add Sydney
# TODO add regional

if (multiLGArun) {
  # More than one LGA so run regional epinow
  print("Generating Multiple LGA estimates...")
  lgaEstimates <- EpiNow2::regional_epinow(reported_cases = lgaCases, 
    generation_time = generation_time,
    delays = delay_opts(incubation_period, reporting_delay),
    # Using default Rt prior
    rt = rt_opts(prior = list(mean = 1, sd = 0.5)),
    stan = stan_opts(),
    target_folder = file.path("results", resultsFolder),
    logs = file.path("logs", Sys.Date()),
    return_output = TRUE, 
    verbose = TRUE)
  
  print("Producing LGA summary ...")
  
  RegionalSummary(lgaEstimates, resultsFolder, dateCases) 
  
  # Run function to save CSV file of key indicators for each region
  for (region in names(lgaEstimates$regional)) {
    regionEstimates <- GetKeyEstimates(lgaEstimates, multiLGArun, region)
    
    SaveAllIndicators(regionEstimates, 
      file.path("results", file.path(resultsFolder, region)),
      dateCases)
    SaveAllIndicators(regionEstimates, 
      file.path("results", file.path(resultsFolder, region)), 
      "latest")
  }
  
} else {
  # 0 or 1 LGAs in lgaRegions
  if (nrow(lgaCases) != 0) {
    print("Generating Single LGA estimates...")
    lgaEstimates <- EpiNow2::epinow(
      reported_cases = dplyr::select(lgaCases, -region),
      generation_time = generation_time,
      delays = delay_opts(incubation_period, reporting_delay),
      # Using default Rt prior
      rt = rt_opts(prior = list(mean = 1, sd = 0.5)),
      stan = stan_opts(),
      target_folder = file.path("results", resultsFolder,
        lgaRegions),
      logs = file.path("logs", Sys.Date()),
      return_output = TRUE, 
      verbose = TRUE)
    
    # Run function to save CSV file of key indicators 
    keyEstimates <- GetKeyEstimates(lgaEstimates, multiLGArun)
    
    SaveAllIndicators(keyEstimates, 
      file.path("results", resultsFolder, lgaRegions),
      dateCases)
    SaveAllIndicators(keyEstimates, 
      file.path("results", resultsFolder, lgaRegions), 
      "latest")
    
  } 
}

print("Tidying up...")
# Save everything in the results folder just in case
save(regionLevel, startDate, dateRun, specificRegions, dataOption, 
  delayOption, cases, nswEstimates, LGAestimates,
  resultsFolder, generation_time, incubation_period, reporting_delay,
  file = file.path("results", resultsFolder, paste0("Epinow_results-", 
    format(Sys.time(), "%Y-%m-%d_%H-%M-%S"), ".rds")))
```

```{r Summarise results}
# Commands for looking at individual region results
# > summary(estimates)
# > plot(estimates)
# > summary(estimates, type = "parameters", params = "R")
```

