# Script for exploring trends in specific regions and areas
# =========================================================

```{r Set-up}
# Open as a project (setting working directory to source and restarting R)

# Packages
require(tidyverse, quietly = TRUE)
require(lubridate, quietly = TRUE)
require(segmented, quietly = TRUE)

options(dplyr.summarise.inform=FALSE)

# Functions 
source("code/GetCases.R")
source("code/LoadData.R")
source("code/SpecifyRegions.R")
source("code/PlotOptions.R")
source("code/Functions.R")

```

```{r User inputs}
# Retrieve cases
dataOption <- "nsw_website" 
nsw_raw_cases <- LoadData(dataOption)

# Case dates
startDate <- "2021-06-01" # Filter to after this date 
dateRun <- NULL # Filter to before this date: NULL = last date in data file

# Specify region
lgaNames <- unique(sort(nsw_raw_cases$lga_name19)) # for reference 

# Specify region if not "NSW", "Greater Sydney", "All Regional NSW", or single LGA
# e.g. "Fairfield (C)", "Sutherland Shire (A)"
regionName <- "Sutherland Shire (A)"

```

```{r Get region cases data}
# Will produce error if there are no cases
cases <- GetCases(nsw_raw_cases, dataOption, startDate)[[1]] %>%
  filter(region == regionName) %>%
  select(-region) %>%
  # Fill in missing dates with zeros
  left_join(tibble(date = as_date(ymd(min(.$date)):ymd(max(.$date))),
    confirm = 0), ., by = "date") %>%
  replace_na(list(confirm.y = 0)) %>%
  mutate(confirm = confirm.x + confirm.y) %>%
  # tidy up
  arrange(date) %>%
  mutate(day = 1:nrow(.)) %>%
  select(date, day, confirm)

tail(cases)
```

```{r Plot of cases}
plotTitle <- regionName
regionPlot <- CasesPlot(cases, plotTitle)

regionPlot

```

```{r}
if (regionName == "Correctional settings") {
  reportedCases1 <- c(0.0,	0.0,	0.1,	0.1,	0.2,	0.2,	0.2,	0.3,	0.3,	
    1.2,	0.4,	0.6,	
    0.7,	0.8,	0.9,	1.1,	1.2,	1.4,	1.6,	1.8,	2.0,	2.3,	2.5,	2.9,
    3.2,	3.6,	4.0,	4.5,	4.9,	5.5,	6.0,	6.6,	7.1,	7.7,	8.3,	8.9,
    9.5,	10.1,	10.6,	11.120754,	11.6,	12.0,	12.4,	12.7,	13.0,	13.2,	13.4,
    13.5,	13.5,	13.5,	13.4,	13.3,	13.2,	13.0,	12.7,	12.5,	12.2,	11.8,	11.5,
    11.1,	10.7, 10.4,	10.0,	9.6,	9.2,	8.8,	8.4,	8.0,	7.6,	7.3,	6.9,	
    6.6,	6.2,	5.9,	5.6,	5.3,	5.0,	4.8,	4.5,	4.3,	4.1,	3.9,	3.7,
    3.5,	3.3,	3.1,	2.9,	2.8,	2.7,	2.5,	2.4,	2.3,	2.2,	2.0,	1.9,	
    1.9,	1.8,	1.7,	1.6,	1.5,	1.4,	1.4,	1.3,	1.3,	1.2,	1.1,	1.1,
    1.0,	1.0,	1.0,	0.9,	0.9,	0.8,	0.8,	0.8,	0.7,	0.7,	0.7,	0.6,
    0.6)
  
  reportedCases2 <- c(0.1, 0.6,	0.7,	0.9,	1.0,	1.2,	1.3,	1.5,	2.6,	2.0,	2.3,	2.6,
    3.0,	3.4,	3.8,	4.2,	4.7,	5.2,	5.7,	6.3,	6.9,	7.5,	8.1,	8.7,
    9.3,	9.9,	10.5,	11.0,	11.5,	12.0,	12.4,	12.8,	13.1,	13.3,	13.5,	13.7,
    13.7,	13.8,	13.721206,	13.6,	13.5,	13.3,	13.1,	12.8,	12.5,	12.2,	11.9,
    11.5,	11.1,	10.7,	10.3,	9.9,	9.5,	9.1,	8.7,	8.3,	7.9,	7.5,	7.2,
    6.8,	6.5,	6.1,	5.8,	5.5,	5.2,	5.0,	4.7,	4.4,	4.2,	4.0,	3.8,
    3.6,	3.4,	3.2,	3.0,	2.9,	2.7,	2.6,	2.5,	2.3,	2.2,	2.1,	2.0,
    1.9,	1.8,	1.7,	1.6,	1.6,	1.5,	1.4,	1.3,	1.3,	1.2,	1.2,	1.1,
    1.1,	1.0,	1.0,	0.9,	0.9,	0.8,	0.8,	0.8,	0.7,	0.7,	0.7,	0.7,
    0.6,	0.6,	0.6,	0.6,	0.5,	0.5,	0.5,	0.5,	0.5,	0.4,	0.4,	0.4)
  
  
  delay <- 0
  
  regionPlot +
    geom_line(aes(y = reportedCases1[(1+delay):(61+delay)]), color = "black") +
    geom_line(aes(y = reportedCases2[(1+delay):(61+delay)]), color = "blue")
}


```

```{r Simple overall trends}
trendCases <- glm(confirm ~ day, data = cases, family = "poisson")
coeff <- exp(coef(trendCases)[2])
p_value <- summary(trendCases)$coefficients["day", "Pr(>|z|)"]
interval <- exp(confint(trendCases, "day", type = "Wald"))

# Add overall trend to plot
regionPlotTrend <- regionPlot +
  geom_line(aes(y = fitted(trendCases)), 
    colour = "black")

regionPlotTrend

```

```{r Segmented trends}
# Initial breakpoint estimates - use trial and error based on visual 
# inspection and test for sensitivity by varying the initial guess of the 
# breakpoint to see if there is any change in the fitted curve. 
breakPoints <- list("single" = mean(cases$day), 
  "double" = c(quantile(cases$day, 0.25), quantile(cases$day, 0.75)))

# Fit segmented model
segModel1 <- segmented(trendCases, seg.Z = ~day, 
  psi = list(day = breakPoints$single))

# segModel2 <- segmented(trendCases, seg.Z = ~day, 
#   psi = list(day = breakPoints$double))

ymax <-1.1*max(cases$confirm)

segPlot <- ggplot(data = cases, 
  aes(x = date, y = confirm)) +
  geom_line(aes(color = "cases")) + 
  geom_point(color = "red") +
  geom_line(aes(y = fitted(trendCases), colour = "overall")) +
  geom_line(aes(y = fitted(segModel1), colour = "segment")) + 
  # expand_limits(y = c(0, ymax)) +
  scale_colour_manual("", values = c("red", "black", "blue"),
    limits = c("cases", "overall", "segment"),
    labels = c("Cases", "Overall model",
      "Segmented model")) +
  labs(x = "Date", y = "Daily cases", title = plotTitle) +
  PlotOptions() +
  geom_vline(xintercept = cases$date[1] + (segModel1$psi[2]-1), 
    linetype = "dashed",
    colour = "blue")

segPlot

```

```{r NLS fit EXPERIMENTAL}
# Experimental chunk looking at NLS fits using a function with 
# exponential increase and decay. 
# NOT WORKING YET. 

# Main model
FitModel <- function(x, a, g, d, k) {
  return(k * a * exp((g-d) * x) / ((k - a) +
      a*exp(g * x)))
}

# Time to peak in model
TP <- function(a, g, d, k) {
  return((1/g) * log((g-d)*(k-a)/(d*a)))
}

# To find good initial conditions requires guessing and checking 
# regionPlot + 
#   geom_line(aes(y = FitModel(1:nrow(cases), 0.1, 0.49, 0.055, 200)), 
#     colour = "dark green")
# 
# # Now run nls() to produce a non-linear model.
# fitModel <- nls(confirm ~ FitModel(day, a, g, d, k), data = cases, 
#   start = list(a = 0.1, g = 0.49, d = 0.055, k = 200),
#   control = nls.control(maxiter = 1000))



```


