# Script to produce a summary plot for specified regions
# ======================================================

# Results need to have been generated by EpiNow first

```{r Set-up}

# Packages
require(EpiNow2, quietly = TRUE)
require(tidyverse, quietly = TRUE)
require(lubridate, quietly = TRUE)

options(dplyr.summarise.inform=FALSE)

# Functions 

# source("code/SpecifyRegions.R")
# source("code/RegionalSummary.R")
# source("code/regional_summary_NSW.R")
source("code/plot_summary_NSW.R")
source("code/RegionsCumulativeReports.R")
source("code/Functions.R")

```


```{r User inputs}

resultsDir <- file.path("results", "All", "LGA-summary", "latest")

```

```{r Functions}
save_ggplot <- function(plot, name, height = 12, width = 12, ...) {
  suppressWarnings(
    suppressMessages(
      ggplot2::ggsave(file.path(resultsDir, name),
        plot,
        dpi = 300, width = width,
        height = height, ...
      )
    )
  )
}
```

```{r Load results}

# Load regional summary results results 
summary_data <- data.table::fread(file.path(resultsDir, "summary_data.csv"))
reported_cases <- data.table::fread(file.path(resultsDir, "reported_cases.csv"))

reported_cases <- data.table::setDT(reported_cases) %>%
  mutate(date = as.Date(date))

```

```{r Separate regions}
# Filter out regions we want

sydneyLGAs <- c("Bayside (A)", "Blacktown (C)", "Blue Mountains (C)", 
  "Burwood (A)", "Camden (A)", "Campbelltown (C) (NSW)", "Canada Bay (A)", 
  "Canterbury-Bankstown (A)", "Central Coast (C) (NSW)", 
  "Cumberland (A)", "Fairfield (C)", "Georges River (A)", "Hawkesbury (C)", 
  "Hornsby (A)", "Hunters Hill (A)", "Inner West (A)", "Ku-ring-gai (A)", 
  "Lane Cove (A)", "Liverpool (C)", "Mosman (A)", "North Sydney (A)", 
  "Northern Beaches (A)", "Parramatta (C)", "Penrith (C)", "Randwick (C)", 
  "Ryde (C)", "Strathfield (A)", "Sutherland Shire (A)", "Sydney (C)", 
  "The Hills Shire (A)", "Waverley (A)", "Willoughby (C)", "Wollondilly (A)", 
  "Wollongong (C)", "Woollahra (A)")

# Sub-regional areas
regionalLGAs <- read_csv("data/list_regionalLHDs_LGA.csv", 
  col_types = cols_only(grouplhd = "c", LHD_NAME = "c", LGA_NAME_2020 ="c")) %>%
  rename(group = grouplhd, lhd = LHD_NAME, lga = LGA_NAME_2020)

northernLGAs <- regionalLGAs %>%  filter(group == "north_region_lhd")
westernLGAs <- regionalLGAs %>%  filter(group == "west_region_lhd")
southernLGAs <- regionalLGAs %>%  filter(group == "south_region_lhd")

summary_data_sydney <- filter(summary_data, region %in% sydneyLGAs)
reported_cases_sydney <- filter(reported_cases, region %in% sydneyLGAs)

summary_data_northern <- filter(summary_data, region %in% northernLGAs$lga)
reported_cases_northern <- filter(reported_cases, region %in% northernLGAs$lga)

summary_data_western <- filter(summary_data, region %in% westernLGAs$lga)
reported_cases_western <- filter(reported_cases, region %in% westernLGAs$lga)

summary_data_southern <- filter(summary_data, region %in% southernLGAs$lga)
reported_cases_southern <- filter(reported_cases, region %in% southernLGAs$lga)

```

```{r produce plots}

# Produce plots for each region
max_plot <- 10

# 
max_cases_sydney <- round(max(reported_cases_sydney$confirm, na.rm = TRUE) * 
    max_plot, 0)
max_cases_northern <- round(max(reported_cases_northern$confirm, na.rm = TRUE) * 
    max_plot, 0)
max_cases_western <- round(max(reported_cases_western$confirm, na.rm = TRUE) * 
    max_plot, 0)
max_cases_southern <- round(max(reported_cases_southern$confirm, na.rm = TRUE) * 
    max_plot, 0)

summary_plot_Sydney <- plot_summary_NSW(summary_data_sydney,
  x_lab = "Region", log_cases = FALSE, max_cases = max_cases_sydney,
  reported_cases = reported_cases_sydney)

summary_plot_Northern <- plot_summary_NSW(summary_data_northern,
  x_lab = "Region", log_cases = FALSE, max_cases = max_cases_northern,
  reported_cases = reported_cases_northern)

summary_plot_Western <- plot_summary_NSW(summary_data_western,
  x_lab = "Region", log_cases = FALSE, max_cases = max_cases_western,
  reported_cases = reported_cases_western)

summary_plot_Southern <- plot_summary_NSW(summary_data_southern,
  x_lab = "Region", log_cases = FALSE, max_cases = max_cases_southern,
  reported_cases = reported_cases_southern)

save_ggplot(summary_plot_Sydney, "summary_plot_SydneyLGAs.png",
  width = ifelse(length(sydneyLGAs) > 60,
    ifelse(length(sydneyLGAs) > 120, 36, 24), 12))

# 
save_ggplot(summary_plot_Northern, "summary_plot_NorthernLGAs.png",
  width = ifelse(length(northernLGAs) > 60,
    ifelse(length(northernLGAs) > 120, 36, 24), 12))

save_ggplot(summary_plot_Western, "summary_plot_WesternLGAs.png",
  width = ifelse(length(westernLGAs) > 60,
    ifelse(length(westernLGAs) > 120, 36, 24), 12))

save_ggplot(summary_plot_Southern, "summary_plot_SouthernLGAs.png",
  width = ifelse(length(southernLGAs) > 60,
    ifelse(length(southernLGAs) > 120, 36, 24), 12))

```
