#' Plot a Summary of the Latest Results for NSW
#'
#' @description
#' A tweak of the EpiNow2 plot_summary() function to produce additional 
#' NSW specific plots summarising results from across regions. It turns
#' the plot to be vertically orientated. 
#' (using results generated by `summarise_results`).
#' May be depreciated in later releases in favour of enhanced S3 methods.
#' @param summary_results A data.table as returned by `summarise_results` (the `data` object).
#' @param x_lab A character string giving the label for the x axis, defaults to region.
#' @param log_cases Logical, should cases be shown on a logged scale. Defaults to `FALSE`
#' @param max_cases Numeric, no default. The maximum number of cases to plot.
#' @param reported_cases A data.table of the reported cases by region.
#' 
#' @return A `ggplot2` object
#' @export
#' @importFrom ggplot2 ggplot aes geom_linerange geom_hline facet_wrap theme 
#' guides labs expand_limits guide_legend element_blank scale_color_manual 
#' .data coord_cartesianscale_y_continuous
#' @importFrom scales comma
#' @importFrom cowplot theme_cowplot panel_border
#' @importFrom patchwork plot_layout
#' @importFrom data.table setDT
plot_summary_NSW <- function(summary_results, x_lab = "Region", 
  log_cases = FALSE, max_cases, reported_cases) {
  
  # set input to data.table
  summary_results <- data.table::setDT(summary_results)
  
  # extract CrIs
  CrIs <- extract_CrIs(summary_results)
  max_CrI <- max(CrIs)
  
  # generic plotting function for cases and rt
  inner_plot <- function(df) {
    plot <- ggplot2::ggplot(df, ggplot2::aes(
      y = region,
      col = `Expected change in daily cases`
    ))
    # plot CrIs
    index <- 1
    alpha_per_CrI <- 0.8 / (length(CrIs) - 1)
    for (CrI in CrIs) {
      bottom <- paste0("lower_", CrI)
      top <- paste0("upper_", CrI)
      plot <- plot +
        ggplot2::geom_linerange(ggplot2::aes(xmin = .data[[bottom]], xmax = .data[[top]]),
          alpha = ifelse(index == 1, 0.4, alpha_per_CrI),
          size = 4
        )
      index <- index + 1
    }

    plot <- plot +
      ggplot2::geom_vline(xintercept = 1, linetype = 2) +
      ggplot2::facet_wrap(~metric, nrow = 1, scales = "free_x") +
      cowplot::theme_cowplot() +
      cowplot::panel_border() +
      ggplot2::scale_color_manual(values = c(
      "Increasing" = "#e75f00",
      "Likely increasing" = "#fd9e49",
      "Likely decreasing" = "#5fa2ce",
      "Decreasing" = "#1170aa",
      "Stable" = "#7b848f"
      ), drop = FALSE)
  }
  
  # Function for extracting the legend
  GetLegend <- function(myggplot){
    
    tmp <- ggplot_gtable(ggplot_build(myggplot))
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
    legend <- tmp$grobs[[leg]]
    
    return(legend)
  }
  
  # check max_cases
  upper_CrI <- paste0("upper_", max_CrI)
  max_upper <- max(summary_results[metric %in% "New confirmed cases by infection date"]$median, #[, ..upper_CrI],
    na.rm = TRUE)
  max_cases <- min(c(max_cases, max_upper + 1), na.rm = TRUE)
  
  # reported cases plot
  reported_weekly_cases <- left_join(
    summary_results[metric %in% "New confirmed cases by infection date"],
    RegionsCumulativeReports(reported_cases), by = "region") %>%
    mutate(metric = "Reported cases in last 7 days") %>%
    arrange(confirm) %>%
    mutate(region = factor(region, levels = .$region))
  
  max_weekly_cases <- max(reported_weekly_cases$confirm)
  
  reported_plot <- ggplot2::ggplot(reported_weekly_cases, 
    ggplot2::aes(y = region,
      colour = `Expected change in daily cases`)) +
    ggplot2::geom_linerange(ggplot2::aes(xmin = 0, xmax = confirm),
      alpha = 0.4, size = 4) +
    ggplot2::facet_wrap(~metric, nrow = 1, scales = "free_x") +
    cowplot::theme_cowplot() +
    cowplot::panel_border() +
    ggplot2::scale_colour_manual(values = c(
      "Increasing" = "#e75f00",
      "Likely increasing" = "#fd9e49",
      "Likely decreasing" = "#5fa2ce",
      "Decreasing" = "#1170aa",
      "Stable" = "#7b848f"
    ), drop = FALSE) +
    ggplot2::labs(y = x_lab, x = "") +
    ggplot2::theme(legend.position = "none")
    
  
  if (log_cases) {
    reported_plot <- reported_plot +
      ggplot2::scale_x_log10(
        labels = scales::comma,
        limits = c(NA, ifelse(!missing(max_cases), max_weekly_cases, NA)),
        oob = scales::squish
      )
  } else {
    reported_plot <- reported_plot +
      ggplot2::scale_x_continuous(
        labels = scales::comma,
        limits = c(NA, ifelse(!missing(max_cases), max_weekly_cases, NA)),
        oob = scales::squish
      )
  }
  
  # rt plot
  rt_data <- summary_results[metric %in% "Effective reproduction no."] 
  rt_data <- left_join(rt_data, RegionsCumulativeReports(reported_cases),
    by = "region") %>%
    arrange(confirm) %>%
    # Arrange LGAs in the same way as for reported weekly cases
    mutate(region = factor(region, levels = reported_weekly_cases$region))
  
  uppers <- grepl("upper_", colnames(rt_data))
  max_rt <- max(data.table::copy(rt_data)[, ..uppers], na.rm = TRUE)
  rt_plot <-
    inner_plot(rt_data) +
    ggplot2::guides(col = ggplot2::guide_legend(nrow = 2)) +
    ggplot2::labs(y = x_lab, x = "") +
    ggplot2::expand_limits(x = c(0, min(max_rt, 8))) +
    ggplot2::coord_cartesian(xlim = c(0, min(max_rt, 8))) +
    ggplot2::theme(
      axis.title.y = ggplot2::element_blank(),
      axis.text.y = ggplot2::element_blank()
    ) +
    ggplot2::theme(legend.position = "bottom")
  
  # join plots together
  legend <- GetLegend(rt_plot)
  rt_plot <- rt_plot + ggplot2::theme(legend.position = "none")
  
  plot <- reported_plot + rt_plot + patchwork::plot_layout(nrow = 1)
  plot <- cowplot::ggdraw() +
    cowplot::draw_plot(plot, 0, 0.05, 1, 0.95) +
    cowplot::draw_plot(legend, 0.2, 0.02, 0.6, 0.05)
  
  return(plot)
}
